# Generated by Django 3.1.1 on 2022-05-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20220507_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='info',
            field=models.CharField(max_length=100),
        ),
    ]
