# Generated by Django 3.1.1 on 2022-05-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20220507_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='info',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
